#!/usr/bin/env python
"""Regenerate the machine-owned region of `progress.md` from `memory.md` + git.

`progress.md` is the human monitoring dashboard. Most of it is *derivable*:
phase counts, current phase/task, last commit, push state. Hand-maintaining it
produced ~11 "fix stale dashboard rows" commits, so the derivable part is now
generated.

Contract:
  - The region between ``<!-- BEGIN AUTO:DASHBOARD -->`` and
    ``<!-- END AUTO:DASHBOARD -->`` is machine-owned. Never edit it by hand.
  - Everything else in `progress.md` is human-owned and preserved verbatim.
  - Sources of truth: `memory.md` (phase table + ``Current Status``) and
    ``git log`` / ``git status``.

Usage:
    python scripts/gen_dashboard.py           # rewrite in place
    python scripts/gen_dashboard.py --check    # exit 1 if out of date (CI)
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MEMORY = REPO / "memory.md"
PROGRESS = REPO / "progress.md"
BEGIN = "<!-- BEGIN AUTO:DASHBOARD -->"
END = "<!-- END AUTO:DASHBOARD -->"

PHASE_ROW = re.compile(
    r"^\|\s*(P\d+)\s+([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]*?)\s*\|\s*([^|]*?)\s*\|\s*$"
)
FIELD = re.compile(r"^-\s+\*\*([^:]+)\*\*:\s*(.*)$")


def parse_phase_table(text: str) -> list[tuple[str, str, str, str, str]]:
    """Return [(phase_id, name, state, gate, signed_by)] from the phase table."""
    rows: list[tuple[str, str, str, str, str]] = []
    seen: set[str] = set()
    for line in text.splitlines():
        m = PHASE_ROW.match(line)
        if not m:
            continue
        phase_id = m.group(1)
        if phase_id in seen:
            continue  # ignore duplicate rows in the source table
        seen.add(phase_id)
        rows.append(
            (
                phase_id,
                m.group(2).strip(),
                m.group(3).strip(),
                m.group(4).strip(),
                m.group(5).strip(),
            )
        )
    return rows


def parse_current_status(text: str) -> dict[str, str]:
    """Return the ``Current Status`` key/value block from memory.md."""
    match = re.search(
        r"^## Current Status\s*$(.*?)(?=^##\s)", text, re.DOTALL | re.MULTILINE
    )
    if not match:
        return {}
    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        m = FIELD.match(line.strip())
        if m:
            fields[m.group(1).strip()] = m.group(2).strip()
    return fields


def git(*args: str) -> str:
    """Run git in the repo and return stdout (empty string on failure)."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=REPO,
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:  # pragma: no cover - git always present in this repo
        return ""
    return result.stdout.strip() if result.returncode == 0 else ""


def render() -> str:
    """Build the machine-owned dashboard block."""
    memory = MEMORY.read_text(encoding="utf-8")
    phases = parse_phase_table(memory)
    status = parse_current_status(memory)

    closed = [p for p in phases if p[2] == "closed"]
    in_progress = [p for p in phases if p[2] == "in progress"]
    remaining = [p for p in phases if p[2] != "closed"]
    total = len(phases) or 1

    current_phase = (
        f"**{in_progress[0][0]} — {in_progress[0][1]}**"
        if in_progress
        else "_(none — all phases closed or blocked)_"
    )
    current_task = status.get("Current task", "_(unset)_")
    next_task = status.get("Next task", "_(unset)_")
    last_commit = git("log", "-1", "--pretty=%h")
    dirty = git("status", "--short")
    pushed = git("rev-list", "-1", "origin/main") == git("rev-list", "-1", "HEAD")
    push_note = "✅ in sync with `origin/main`" if pushed else "⚠️ not pushed"

    return "\n".join(
        [
            BEGIN,
            (
                "_Auto-generated by `scripts/gen_dashboard.py` from `memory.md` + git. "
                "Do not edit by hand \u2014 run the script instead._"
            ),
            "",
            "## Overall Progress",
            "",
            "| Metric | Value |",
            "| :--- | :--- |",
            (
                f"| Phases closed | **{len(closed)} / {total}** "
                f"({', '.join(p[0] for p in closed) or '—'}) |"
            ),
            (
                f"| Phases in progress | **{len(in_progress)}** "
                f"({', '.join(p[0] for p in in_progress) or '—'}) |"
            ),
            (
                f"| Phases remaining | **{len(remaining)}** "
                f"({', '.join(p[0] for p in remaining) or '—'}) |"
            ),
            f"| Current phase | {current_phase} |",
            f"| Current task | {current_task} |",
            f"| Last commit | `{last_commit or '?'}` — {push_note} |",
            "",
            "## Resume Point",
            "",
            (
                "> **The orchestrator resumes from here on every invocation.** "
                "Locate \u2192 verify \u2192 continue. Never restart."
            ),
            "",
            "| Field | Value |",
            "| :--- | :--- |",
            f"| Last completed task | {status.get('Last completed task', '_(unset)_')} |",
            f"| Next task | {next_task} |",
            f"| Last commit | `{last_commit or '?'}` |",
            f"| Working tree | {'dirty (' + str(len(dirty.splitlines())) + ' paths)' if dirty else 'clean'} |",
            "",
            "## Phase Status",
            "",
            "| Phase | State | Gate | Signed by |",
            "| :--- | :--- | :--- | :--- |",
            *[
                f"| {phase_id} {name} | {state} | {gate} | {signed} |"
                for phase_id, name, state, gate, signed in phases
            ],
            END,
            "",
        ]
    )


def splice(text: str, block: str) -> str:
    """Replace the marked region in ``text`` with ``block``."""
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(
            "progress.md is missing the dashboard markers "
            f"({BEGIN} / {END}); add them once, then re-run."
        )
    return text[:start] + block + text[end + len(END) + 1 :]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the dashboard is out of date (do not write)",
    )
    args = parser.parse_args()

    current = PROGRESS.read_text(encoding="utf-8")
    updated = splice(current, render())

    if args.check:
        if current != updated:
            print(
                "progress.md dashboard is stale; run scripts/gen_dashboard.py",
                file=sys.stderr,
            )
            return 1
        print("dashboard up to date")
        return 0

    PROGRESS.write_text(updated, encoding="utf-8")
    print("dashboard regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
